//
// Created by gacova on 14/05/19.
//

#ifndef GLADIADORESSERVER_ALGORITMOGENETICO_H
#define GLADIADORESSERVER_ALGORITMOGENETICO_H


class AlgoritmoGenetico {

};


#endif //GLADIADORESSERVER_ALGORITMOGENETICO_H
