/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *C1;
    QLabel *C2;
    QLabel *C3;
    QLabel *C4;
    QLabel *C5;
    QLabel *C6;
    QLabel *C7;
    QLabel *C8;
    QLabel *C9;
    QLabel *C10;
    QLabel *C21;
    QLabel *C11;
    QLabel *C31;
    QLabel *C41;
    QLabel *C51;
    QLabel *C61;
    QLabel *C71;
    QLabel *C81;
    QLabel *C91;
    QLabel *C12;
    QLabel *C22;
    QLabel *C32;
    QLabel *C42;
    QLabel *C52;
    QLabel *C62;
    QLabel *C72;
    QLabel *C82;
    QLabel *C92;
    QLabel *C13;
    QLabel *C63;
    QLabel *C23;
    QLabel *C43;
    QLabel *C93;
    QLabel *C73;
    QLabel *C83;
    QLabel *C53;
    QLabel *C33;
    QLabel *C74;
    QLabel *C14;
    QLabel *C94;
    QLabel *C64;
    QLabel *C34;
    QLabel *C54;
    QLabel *C24;
    QLabel *C44;
    QLabel *C84;
    QLabel *C75;
    QLabel *C15;
    QLabel *C95;
    QLabel *C65;
    QLabel *C35;
    QLabel *C55;
    QLabel *C25;
    QLabel *C45;
    QLabel *C85;
    QLabel *C76;
    QLabel *C16;
    QLabel *C96;
    QLabel *C66;
    QLabel *C36;
    QLabel *C56;
    QLabel *C26;
    QLabel *C46;
    QLabel *C86;
    QLabel *C77;
    QLabel *C17;
    QLabel *C97;
    QLabel *C67;
    QLabel *C37;
    QLabel *C57;
    QLabel *C27;
    QLabel *C47;
    QLabel *C87;
    QLabel *C78;
    QLabel *C18;
    QLabel *C98;
    QLabel *C68;
    QLabel *C38;
    QLabel *C58;
    QLabel *C28;
    QLabel *C48;
    QLabel *C88;
    QLabel *C79;
    QLabel *C19;
    QLabel *C99;
    QLabel *C69;
    QLabel *C39;
    QLabel *C59;
    QLabel *C29;
    QLabel *C49;
    QLabel *C89;
    QLabel *C80;
    QLabel *C20;
    QLabel *C100;
    QLabel *C70;
    QLabel *C40;
    QLabel *C60;
    QLabel *C30;
    QLabel *C50;
    QLabel *C90;
    QPushButton *crearmat;
    QLabel *G2;
    QLabel *G1;
    QPushButton *pushButton;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1297, 870);
        MainWindow->setAutoFillBackground(true);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        C1 = new QLabel(centralWidget);
        C1->setObjectName(QString::fromUtf8("C1"));
        C1->setGeometry(QRect(300, 0, 80, 80));
        C1->setAutoFillBackground(false);
        C1->setFrameShape(QFrame::NoFrame);
        C1->setTextFormat(Qt::PlainText);
        C1->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C1->setScaledContents(false);
        C2 = new QLabel(centralWidget);
        C2->setObjectName(QString::fromUtf8("C2"));
        C2->setGeometry(QRect(380, 0, 80, 80));
        C2->setAutoFillBackground(true);
        C2->setFrameShape(QFrame::NoFrame);
        C2->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C2->setScaledContents(false);
        C3 = new QLabel(centralWidget);
        C3->setObjectName(QString::fromUtf8("C3"));
        C3->setGeometry(QRect(460, 0, 80, 80));
        C3->setAutoFillBackground(true);
        C3->setFrameShape(QFrame::NoFrame);
        C3->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C3->setScaledContents(false);
        C4 = new QLabel(centralWidget);
        C4->setObjectName(QString::fromUtf8("C4"));
        C4->setGeometry(QRect(540, 0, 80, 80));
        C4->setAutoFillBackground(true);
        C4->setFrameShape(QFrame::NoFrame);
        C4->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C4->setScaledContents(false);
        C5 = new QLabel(centralWidget);
        C5->setObjectName(QString::fromUtf8("C5"));
        C5->setGeometry(QRect(620, 0, 80, 80));
        C5->setAutoFillBackground(true);
        C5->setFrameShape(QFrame::NoFrame);
        C5->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C5->setScaledContents(false);
        C6 = new QLabel(centralWidget);
        C6->setObjectName(QString::fromUtf8("C6"));
        C6->setGeometry(QRect(700, 0, 80, 80));
        C6->setAutoFillBackground(true);
        C6->setFrameShape(QFrame::NoFrame);
        C6->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C6->setScaledContents(false);
        C7 = new QLabel(centralWidget);
        C7->setObjectName(QString::fromUtf8("C7"));
        C7->setGeometry(QRect(780, 0, 80, 80));
        C7->setAutoFillBackground(true);
        C7->setFrameShape(QFrame::NoFrame);
        C7->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C7->setScaledContents(false);
        C8 = new QLabel(centralWidget);
        C8->setObjectName(QString::fromUtf8("C8"));
        C8->setGeometry(QRect(860, 0, 80, 80));
        C8->setAutoFillBackground(true);
        C8->setFrameShape(QFrame::NoFrame);
        C8->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C8->setScaledContents(false);
        C9 = new QLabel(centralWidget);
        C9->setObjectName(QString::fromUtf8("C9"));
        C9->setGeometry(QRect(940, 0, 80, 80));
        C9->setAutoFillBackground(true);
        C9->setFrameShape(QFrame::NoFrame);
        C9->setPixmap(QPixmap(QString::fromUtf8("caminoTVerticalAbajo.jpg")));
        C9->setScaledContents(false);
        C10 = new QLabel(centralWidget);
        C10->setObjectName(QString::fromUtf8("C10"));
        C10->setGeometry(QRect(1020, 0, 80, 80));
        C10->setAutoFillBackground(true);
        C10->setFrameShape(QFrame::NoFrame);
        C10->setTextFormat(Qt::PlainText);
        C10->setPixmap(QPixmap(QString::fromUtf8("caminoCurvaHV.jpg")));
        C10->setScaledContents(false);
        C21 = new QLabel(centralWidget);
        C21->setObjectName(QString::fromUtf8("C21"));
        C21->setGeometry(QRect(300, 160, 80, 80));
        C21->setAutoFillBackground(true);
        C21->setFrameShape(QFrame::NoFrame);
        C21->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C21->setScaledContents(false);
        C11 = new QLabel(centralWidget);
        C11->setObjectName(QString::fromUtf8("C11"));
        C11->setGeometry(QRect(300, 80, 80, 80));
        C11->setAutoFillBackground(true);
        C11->setFrameShape(QFrame::NoFrame);
        C11->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C11->setScaledContents(false);
        C31 = new QLabel(centralWidget);
        C31->setObjectName(QString::fromUtf8("C31"));
        C31->setGeometry(QRect(300, 240, 80, 80));
        C31->setAutoFillBackground(true);
        C31->setFrameShape(QFrame::NoFrame);
        C31->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C31->setScaledContents(false);
        C41 = new QLabel(centralWidget);
        C41->setObjectName(QString::fromUtf8("C41"));
        C41->setGeometry(QRect(300, 320, 80, 80));
        C41->setAutoFillBackground(true);
        C41->setFrameShape(QFrame::NoFrame);
        C41->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C41->setScaledContents(false);
        C51 = new QLabel(centralWidget);
        C51->setObjectName(QString::fromUtf8("C51"));
        C51->setGeometry(QRect(300, 400, 80, 80));
        C51->setAutoFillBackground(true);
        C51->setFrameShape(QFrame::NoFrame);
        C51->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C51->setScaledContents(false);
        C61 = new QLabel(centralWidget);
        C61->setObjectName(QString::fromUtf8("C61"));
        C61->setGeometry(QRect(300, 480, 80, 80));
        C61->setAutoFillBackground(true);
        C61->setFrameShape(QFrame::NoFrame);
        C61->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C61->setScaledContents(false);
        C71 = new QLabel(centralWidget);
        C71->setObjectName(QString::fromUtf8("C71"));
        C71->setGeometry(QRect(300, 560, 80, 80));
        C71->setAutoFillBackground(true);
        C71->setFrameShape(QFrame::NoFrame);
        C71->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C71->setScaledContents(false);
        C81 = new QLabel(centralWidget);
        C81->setObjectName(QString::fromUtf8("C81"));
        C81->setGeometry(QRect(300, 640, 80, 80));
        C81->setAutoFillBackground(true);
        C81->setFrameShape(QFrame::NoFrame);
        C81->setPixmap(QPixmap(QString::fromUtf8("caminoTizquierda.jpg")));
        C81->setScaledContents(false);
        C91 = new QLabel(centralWidget);
        C91->setObjectName(QString::fromUtf8("C91"));
        C91->setGeometry(QRect(300, 720, 80, 80));
        C91->setAutoFillBackground(true);
        C91->setFrameShape(QFrame::NoFrame);
        C91->setPixmap(QPixmap(QString::fromUtf8("caminoCurvaVH.jpg")));
        C91->setScaledContents(false);
        C12 = new QLabel(centralWidget);
        C12->setObjectName(QString::fromUtf8("C12"));
        C12->setGeometry(QRect(380, 80, 80, 80));
        C12->setAutoFillBackground(true);
        C12->setFrameShape(QFrame::NoFrame);
        C12->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C12->setScaledContents(false);
        C22 = new QLabel(centralWidget);
        C22->setObjectName(QString::fromUtf8("C22"));
        C22->setGeometry(QRect(380, 160, 80, 80));
        C22->setAutoFillBackground(true);
        C22->setFrameShape(QFrame::NoFrame);
        C22->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C22->setScaledContents(false);
        C32 = new QLabel(centralWidget);
        C32->setObjectName(QString::fromUtf8("C32"));
        C32->setGeometry(QRect(380, 240, 80, 80));
        C32->setAutoFillBackground(true);
        C32->setFrameShape(QFrame::NoFrame);
        C32->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C32->setScaledContents(false);
        C42 = new QLabel(centralWidget);
        C42->setObjectName(QString::fromUtf8("C42"));
        C42->setGeometry(QRect(380, 320, 80, 80));
        C42->setAutoFillBackground(true);
        C42->setFrameShape(QFrame::NoFrame);
        C42->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C42->setScaledContents(false);
        C52 = new QLabel(centralWidget);
        C52->setObjectName(QString::fromUtf8("C52"));
        C52->setGeometry(QRect(380, 400, 80, 80));
        C52->setAutoFillBackground(true);
        C52->setFrameShape(QFrame::NoFrame);
        C52->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C52->setScaledContents(false);
        C62 = new QLabel(centralWidget);
        C62->setObjectName(QString::fromUtf8("C62"));
        C62->setGeometry(QRect(380, 480, 80, 80));
        C62->setAutoFillBackground(true);
        C62->setFrameShape(QFrame::NoFrame);
        C62->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C62->setScaledContents(false);
        C72 = new QLabel(centralWidget);
        C72->setObjectName(QString::fromUtf8("C72"));
        C72->setGeometry(QRect(380, 560, 80, 80));
        C72->setAutoFillBackground(true);
        C72->setFrameShape(QFrame::NoFrame);
        C72->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C72->setScaledContents(false);
        C82 = new QLabel(centralWidget);
        C82->setObjectName(QString::fromUtf8("C82"));
        C82->setGeometry(QRect(380, 640, 80, 80));
        C82->setAutoFillBackground(true);
        C82->setFrameShape(QFrame::NoFrame);
        C82->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C82->setScaledContents(false);
        C92 = new QLabel(centralWidget);
        C92->setObjectName(QString::fromUtf8("C92"));
        C92->setGeometry(QRect(380, 720, 80, 80));
        C92->setAutoFillBackground(true);
        C92->setFrameShape(QFrame::NoFrame);
        C92->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C92->setScaledContents(false);
        C13 = new QLabel(centralWidget);
        C13->setObjectName(QString::fromUtf8("C13"));
        C13->setGeometry(QRect(460, 80, 80, 80));
        C13->setAutoFillBackground(true);
        C13->setFrameShape(QFrame::NoFrame);
        C13->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C13->setScaledContents(false);
        C63 = new QLabel(centralWidget);
        C63->setObjectName(QString::fromUtf8("C63"));
        C63->setGeometry(QRect(460, 480, 80, 80));
        C63->setAutoFillBackground(true);
        C63->setFrameShape(QFrame::NoFrame);
        C63->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C63->setScaledContents(false);
        C23 = new QLabel(centralWidget);
        C23->setObjectName(QString::fromUtf8("C23"));
        C23->setGeometry(QRect(460, 160, 80, 80));
        C23->setAutoFillBackground(true);
        C23->setFrameShape(QFrame::NoFrame);
        C23->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C23->setScaledContents(false);
        C43 = new QLabel(centralWidget);
        C43->setObjectName(QString::fromUtf8("C43"));
        C43->setGeometry(QRect(460, 320, 80, 80));
        C43->setAutoFillBackground(true);
        C43->setFrameShape(QFrame::NoFrame);
        C43->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C43->setScaledContents(false);
        C93 = new QLabel(centralWidget);
        C93->setObjectName(QString::fromUtf8("C93"));
        C93->setGeometry(QRect(460, 720, 80, 80));
        C93->setAutoFillBackground(true);
        C93->setFrameShape(QFrame::NoFrame);
        C93->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C93->setScaledContents(false);
        C73 = new QLabel(centralWidget);
        C73->setObjectName(QString::fromUtf8("C73"));
        C73->setGeometry(QRect(460, 560, 80, 80));
        C73->setAutoFillBackground(true);
        C73->setFrameShape(QFrame::NoFrame);
        C73->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C73->setScaledContents(false);
        C83 = new QLabel(centralWidget);
        C83->setObjectName(QString::fromUtf8("C83"));
        C83->setGeometry(QRect(460, 640, 80, 80));
        C83->setAutoFillBackground(true);
        C83->setFrameShape(QFrame::NoFrame);
        C83->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C83->setScaledContents(false);
        C53 = new QLabel(centralWidget);
        C53->setObjectName(QString::fromUtf8("C53"));
        C53->setGeometry(QRect(460, 400, 80, 80));
        C53->setAutoFillBackground(true);
        C53->setFrameShape(QFrame::NoFrame);
        C53->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C53->setScaledContents(false);
        C33 = new QLabel(centralWidget);
        C33->setObjectName(QString::fromUtf8("C33"));
        C33->setGeometry(QRect(460, 240, 80, 80));
        C33->setAutoFillBackground(true);
        C33->setFrameShape(QFrame::NoFrame);
        C33->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C33->setScaledContents(false);
        C74 = new QLabel(centralWidget);
        C74->setObjectName(QString::fromUtf8("C74"));
        C74->setGeometry(QRect(540, 560, 80, 80));
        C74->setAutoFillBackground(true);
        C74->setFrameShape(QFrame::NoFrame);
        C74->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C74->setScaledContents(false);
        C14 = new QLabel(centralWidget);
        C14->setObjectName(QString::fromUtf8("C14"));
        C14->setGeometry(QRect(540, 80, 80, 80));
        C14->setAutoFillBackground(true);
        C14->setFrameShape(QFrame::NoFrame);
        C14->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C14->setScaledContents(false);
        C94 = new QLabel(centralWidget);
        C94->setObjectName(QString::fromUtf8("C94"));
        C94->setGeometry(QRect(540, 720, 80, 80));
        C94->setAutoFillBackground(true);
        C94->setFrameShape(QFrame::NoFrame);
        C94->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C94->setScaledContents(false);
        C64 = new QLabel(centralWidget);
        C64->setObjectName(QString::fromUtf8("C64"));
        C64->setGeometry(QRect(540, 480, 80, 80));
        C64->setAutoFillBackground(true);
        C64->setFrameShape(QFrame::NoFrame);
        C64->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C64->setScaledContents(false);
        C34 = new QLabel(centralWidget);
        C34->setObjectName(QString::fromUtf8("C34"));
        C34->setGeometry(QRect(540, 240, 80, 80));
        C34->setAutoFillBackground(true);
        C34->setFrameShape(QFrame::NoFrame);
        C34->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C34->setScaledContents(false);
        C54 = new QLabel(centralWidget);
        C54->setObjectName(QString::fromUtf8("C54"));
        C54->setGeometry(QRect(540, 400, 80, 80));
        C54->setAutoFillBackground(true);
        C54->setFrameShape(QFrame::NoFrame);
        C54->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C54->setScaledContents(false);
        C24 = new QLabel(centralWidget);
        C24->setObjectName(QString::fromUtf8("C24"));
        C24->setGeometry(QRect(540, 160, 80, 80));
        C24->setAutoFillBackground(true);
        C24->setFrameShape(QFrame::NoFrame);
        C24->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C24->setScaledContents(false);
        C44 = new QLabel(centralWidget);
        C44->setObjectName(QString::fromUtf8("C44"));
        C44->setGeometry(QRect(540, 320, 80, 80));
        C44->setAutoFillBackground(true);
        C44->setFrameShape(QFrame::NoFrame);
        C44->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C44->setScaledContents(false);
        C84 = new QLabel(centralWidget);
        C84->setObjectName(QString::fromUtf8("C84"));
        C84->setGeometry(QRect(540, 640, 80, 80));
        C84->setAutoFillBackground(true);
        C84->setFrameShape(QFrame::NoFrame);
        C84->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C84->setScaledContents(false);
        C75 = new QLabel(centralWidget);
        C75->setObjectName(QString::fromUtf8("C75"));
        C75->setGeometry(QRect(620, 560, 80, 80));
        C75->setAutoFillBackground(true);
        C75->setFrameShape(QFrame::NoFrame);
        C75->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C75->setScaledContents(false);
        C15 = new QLabel(centralWidget);
        C15->setObjectName(QString::fromUtf8("C15"));
        C15->setGeometry(QRect(620, 80, 80, 80));
        C15->setAutoFillBackground(true);
        C15->setFrameShape(QFrame::NoFrame);
        C15->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C15->setScaledContents(false);
        C95 = new QLabel(centralWidget);
        C95->setObjectName(QString::fromUtf8("C95"));
        C95->setGeometry(QRect(620, 720, 80, 80));
        C95->setAutoFillBackground(true);
        C95->setFrameShape(QFrame::NoFrame);
        C95->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C95->setScaledContents(false);
        C65 = new QLabel(centralWidget);
        C65->setObjectName(QString::fromUtf8("C65"));
        C65->setGeometry(QRect(620, 480, 80, 80));
        C65->setAutoFillBackground(true);
        C65->setFrameShape(QFrame::NoFrame);
        C65->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C65->setScaledContents(false);
        C35 = new QLabel(centralWidget);
        C35->setObjectName(QString::fromUtf8("C35"));
        C35->setGeometry(QRect(620, 240, 80, 80));
        C35->setAutoFillBackground(true);
        C35->setFrameShape(QFrame::NoFrame);
        C35->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C35->setScaledContents(false);
        C55 = new QLabel(centralWidget);
        C55->setObjectName(QString::fromUtf8("C55"));
        C55->setGeometry(QRect(620, 400, 80, 80));
        C55->setAutoFillBackground(true);
        C55->setFrameShape(QFrame::NoFrame);
        C55->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C55->setScaledContents(false);
        C25 = new QLabel(centralWidget);
        C25->setObjectName(QString::fromUtf8("C25"));
        C25->setGeometry(QRect(620, 160, 80, 80));
        C25->setAutoFillBackground(true);
        C25->setFrameShape(QFrame::NoFrame);
        C25->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C25->setScaledContents(false);
        C45 = new QLabel(centralWidget);
        C45->setObjectName(QString::fromUtf8("C45"));
        C45->setGeometry(QRect(620, 320, 80, 80));
        C45->setAutoFillBackground(true);
        C45->setFrameShape(QFrame::NoFrame);
        C45->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C45->setScaledContents(false);
        C85 = new QLabel(centralWidget);
        C85->setObjectName(QString::fromUtf8("C85"));
        C85->setGeometry(QRect(620, 640, 80, 80));
        C85->setAutoFillBackground(true);
        C85->setFrameShape(QFrame::NoFrame);
        C85->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C85->setScaledContents(false);
        C76 = new QLabel(centralWidget);
        C76->setObjectName(QString::fromUtf8("C76"));
        C76->setGeometry(QRect(700, 560, 80, 80));
        C76->setAutoFillBackground(true);
        C76->setFrameShape(QFrame::NoFrame);
        C76->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C76->setScaledContents(false);
        C16 = new QLabel(centralWidget);
        C16->setObjectName(QString::fromUtf8("C16"));
        C16->setGeometry(QRect(700, 80, 80, 80));
        C16->setAutoFillBackground(true);
        C16->setFrameShape(QFrame::NoFrame);
        C16->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C16->setScaledContents(false);
        C96 = new QLabel(centralWidget);
        C96->setObjectName(QString::fromUtf8("C96"));
        C96->setGeometry(QRect(700, 720, 80, 80));
        C96->setAutoFillBackground(true);
        C96->setFrameShape(QFrame::NoFrame);
        C96->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C96->setScaledContents(false);
        C66 = new QLabel(centralWidget);
        C66->setObjectName(QString::fromUtf8("C66"));
        C66->setGeometry(QRect(700, 480, 80, 80));
        C66->setAutoFillBackground(true);
        C66->setFrameShape(QFrame::NoFrame);
        C66->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C66->setScaledContents(false);
        C36 = new QLabel(centralWidget);
        C36->setObjectName(QString::fromUtf8("C36"));
        C36->setGeometry(QRect(700, 240, 80, 80));
        C36->setAutoFillBackground(true);
        C36->setFrameShape(QFrame::NoFrame);
        C36->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C36->setScaledContents(false);
        C56 = new QLabel(centralWidget);
        C56->setObjectName(QString::fromUtf8("C56"));
        C56->setGeometry(QRect(700, 400, 80, 80));
        C56->setAutoFillBackground(true);
        C56->setFrameShape(QFrame::NoFrame);
        C56->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C56->setScaledContents(false);
        C26 = new QLabel(centralWidget);
        C26->setObjectName(QString::fromUtf8("C26"));
        C26->setGeometry(QRect(700, 160, 80, 80));
        C26->setAutoFillBackground(true);
        C26->setFrameShape(QFrame::NoFrame);
        C26->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C26->setScaledContents(false);
        C46 = new QLabel(centralWidget);
        C46->setObjectName(QString::fromUtf8("C46"));
        C46->setGeometry(QRect(700, 320, 80, 80));
        C46->setAutoFillBackground(true);
        C46->setFrameShape(QFrame::NoFrame);
        C46->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C46->setScaledContents(false);
        C86 = new QLabel(centralWidget);
        C86->setObjectName(QString::fromUtf8("C86"));
        C86->setGeometry(QRect(700, 640, 80, 80));
        C86->setAutoFillBackground(true);
        C86->setFrameShape(QFrame::NoFrame);
        C86->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C86->setScaledContents(false);
        C77 = new QLabel(centralWidget);
        C77->setObjectName(QString::fromUtf8("C77"));
        C77->setGeometry(QRect(780, 560, 80, 80));
        C77->setAutoFillBackground(true);
        C77->setFrameShape(QFrame::NoFrame);
        C77->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C77->setScaledContents(false);
        C17 = new QLabel(centralWidget);
        C17->setObjectName(QString::fromUtf8("C17"));
        C17->setGeometry(QRect(780, 80, 80, 80));
        C17->setAutoFillBackground(true);
        C17->setFrameShape(QFrame::NoFrame);
        C17->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C17->setScaledContents(false);
        C97 = new QLabel(centralWidget);
        C97->setObjectName(QString::fromUtf8("C97"));
        C97->setGeometry(QRect(780, 720, 80, 80));
        C97->setAutoFillBackground(true);
        C97->setFrameShape(QFrame::NoFrame);
        C97->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C97->setScaledContents(false);
        C67 = new QLabel(centralWidget);
        C67->setObjectName(QString::fromUtf8("C67"));
        C67->setGeometry(QRect(780, 480, 80, 80));
        C67->setAutoFillBackground(true);
        C67->setFrameShape(QFrame::NoFrame);
        C67->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C67->setScaledContents(false);
        C37 = new QLabel(centralWidget);
        C37->setObjectName(QString::fromUtf8("C37"));
        C37->setGeometry(QRect(780, 240, 80, 80));
        C37->setAutoFillBackground(true);
        C37->setFrameShape(QFrame::NoFrame);
        C37->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C37->setScaledContents(false);
        C57 = new QLabel(centralWidget);
        C57->setObjectName(QString::fromUtf8("C57"));
        C57->setGeometry(QRect(780, 400, 80, 80));
        C57->setAutoFillBackground(true);
        C57->setFrameShape(QFrame::NoFrame);
        C57->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C57->setScaledContents(false);
        C27 = new QLabel(centralWidget);
        C27->setObjectName(QString::fromUtf8("C27"));
        C27->setGeometry(QRect(780, 160, 80, 80));
        C27->setAutoFillBackground(true);
        C27->setFrameShape(QFrame::NoFrame);
        C27->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C27->setScaledContents(false);
        C47 = new QLabel(centralWidget);
        C47->setObjectName(QString::fromUtf8("C47"));
        C47->setGeometry(QRect(780, 320, 80, 80));
        C47->setAutoFillBackground(true);
        C47->setFrameShape(QFrame::NoFrame);
        C47->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C47->setScaledContents(false);
        C87 = new QLabel(centralWidget);
        C87->setObjectName(QString::fromUtf8("C87"));
        C87->setGeometry(QRect(780, 640, 80, 80));
        C87->setAutoFillBackground(true);
        C87->setFrameShape(QFrame::NoFrame);
        C87->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C87->setScaledContents(false);
        C78 = new QLabel(centralWidget);
        C78->setObjectName(QString::fromUtf8("C78"));
        C78->setGeometry(QRect(860, 560, 80, 80));
        C78->setAutoFillBackground(true);
        C78->setFrameShape(QFrame::NoFrame);
        C78->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C78->setScaledContents(false);
        C18 = new QLabel(centralWidget);
        C18->setObjectName(QString::fromUtf8("C18"));
        C18->setGeometry(QRect(860, 80, 80, 80));
        C18->setAutoFillBackground(true);
        C18->setFrameShape(QFrame::NoFrame);
        C18->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C18->setScaledContents(false);
        C98 = new QLabel(centralWidget);
        C98->setObjectName(QString::fromUtf8("C98"));
        C98->setGeometry(QRect(860, 720, 80, 80));
        C98->setAutoFillBackground(true);
        C98->setFrameShape(QFrame::NoFrame);
        C98->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C98->setScaledContents(false);
        C68 = new QLabel(centralWidget);
        C68->setObjectName(QString::fromUtf8("C68"));
        C68->setGeometry(QRect(860, 480, 80, 80));
        C68->setAutoFillBackground(true);
        C68->setFrameShape(QFrame::NoFrame);
        C68->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C68->setScaledContents(false);
        C38 = new QLabel(centralWidget);
        C38->setObjectName(QString::fromUtf8("C38"));
        C38->setGeometry(QRect(860, 240, 80, 80));
        C38->setAutoFillBackground(true);
        C38->setFrameShape(QFrame::NoFrame);
        C38->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C38->setScaledContents(false);
        C58 = new QLabel(centralWidget);
        C58->setObjectName(QString::fromUtf8("C58"));
        C58->setGeometry(QRect(860, 400, 80, 80));
        C58->setAutoFillBackground(true);
        C58->setFrameShape(QFrame::NoFrame);
        C58->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C58->setScaledContents(false);
        C28 = new QLabel(centralWidget);
        C28->setObjectName(QString::fromUtf8("C28"));
        C28->setGeometry(QRect(860, 160, 80, 80));
        C28->setAutoFillBackground(true);
        C28->setFrameShape(QFrame::NoFrame);
        C28->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C28->setScaledContents(false);
        C48 = new QLabel(centralWidget);
        C48->setObjectName(QString::fromUtf8("C48"));
        C48->setGeometry(QRect(860, 320, 80, 80));
        C48->setAutoFillBackground(true);
        C48->setFrameShape(QFrame::NoFrame);
        C48->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C48->setScaledContents(false);
        C88 = new QLabel(centralWidget);
        C88->setObjectName(QString::fromUtf8("C88"));
        C88->setGeometry(QRect(860, 640, 80, 80));
        C88->setAutoFillBackground(true);
        C88->setFrameShape(QFrame::NoFrame);
        C88->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C88->setScaledContents(false);
        C79 = new QLabel(centralWidget);
        C79->setObjectName(QString::fromUtf8("C79"));
        C79->setGeometry(QRect(940, 560, 80, 80));
        C79->setAutoFillBackground(true);
        C79->setFrameShape(QFrame::NoFrame);
        C79->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C79->setScaledContents(false);
        C19 = new QLabel(centralWidget);
        C19->setObjectName(QString::fromUtf8("C19"));
        C19->setGeometry(QRect(940, 80, 80, 80));
        C19->setAutoFillBackground(true);
        C19->setFrameShape(QFrame::NoFrame);
        C19->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C19->setScaledContents(false);
        C99 = new QLabel(centralWidget);
        C99->setObjectName(QString::fromUtf8("C99"));
        C99->setGeometry(QRect(940, 720, 80, 80));
        C99->setAutoFillBackground(true);
        C99->setFrameShape(QFrame::NoFrame);
        C99->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C99->setScaledContents(false);
        C69 = new QLabel(centralWidget);
        C69->setObjectName(QString::fromUtf8("C69"));
        C69->setGeometry(QRect(940, 480, 80, 80));
        C69->setAutoFillBackground(true);
        C69->setFrameShape(QFrame::NoFrame);
        C69->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C69->setScaledContents(false);
        C39 = new QLabel(centralWidget);
        C39->setObjectName(QString::fromUtf8("C39"));
        C39->setGeometry(QRect(940, 240, 80, 80));
        C39->setAutoFillBackground(true);
        C39->setFrameShape(QFrame::NoFrame);
        C39->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C39->setScaledContents(false);
        C59 = new QLabel(centralWidget);
        C59->setObjectName(QString::fromUtf8("C59"));
        C59->setGeometry(QRect(940, 400, 80, 80));
        C59->setAutoFillBackground(true);
        C59->setFrameShape(QFrame::NoFrame);
        C59->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C59->setScaledContents(false);
        C29 = new QLabel(centralWidget);
        C29->setObjectName(QString::fromUtf8("C29"));
        C29->setGeometry(QRect(940, 160, 80, 80));
        C29->setAutoFillBackground(true);
        C29->setFrameShape(QFrame::NoFrame);
        C29->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C29->setScaledContents(false);
        C49 = new QLabel(centralWidget);
        C49->setObjectName(QString::fromUtf8("C49"));
        C49->setGeometry(QRect(940, 320, 80, 80));
        C49->setAutoFillBackground(true);
        C49->setFrameShape(QFrame::NoFrame);
        C49->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C49->setScaledContents(false);
        C89 = new QLabel(centralWidget);
        C89->setObjectName(QString::fromUtf8("C89"));
        C89->setGeometry(QRect(940, 640, 80, 80));
        C89->setAutoFillBackground(true);
        C89->setFrameShape(QFrame::NoFrame);
        C89->setPixmap(QPixmap(QString::fromUtf8("caminoT.jpg")));
        C89->setScaledContents(false);
        C80 = new QLabel(centralWidget);
        C80->setObjectName(QString::fromUtf8("C80"));
        C80->setGeometry(QRect(1020, 560, 80, 80));
        C80->setAutoFillBackground(true);
        C80->setFrameShape(QFrame::NoFrame);
        C80->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C80->setScaledContents(false);
        C20 = new QLabel(centralWidget);
        C20->setObjectName(QString::fromUtf8("C20"));
        C20->setGeometry(QRect(1020, 80, 80, 80));
        C20->setAutoFillBackground(true);
        C20->setFrameShape(QFrame::NoFrame);
        C20->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C20->setScaledContents(false);
        C100 = new QLabel(centralWidget);
        C100->setObjectName(QString::fromUtf8("C100"));
        C100->setGeometry(QRect(1020, 720, 80, 80));
        C100->setAutoFillBackground(true);
        C100->setFrameShape(QFrame::NoFrame);
        C100->setPixmap(QPixmap(QString::fromUtf8("caminoTHorizontalArriba.jpg")));
        C100->setScaledContents(false);
        C70 = new QLabel(centralWidget);
        C70->setObjectName(QString::fromUtf8("C70"));
        C70->setGeometry(QRect(1020, 480, 80, 80));
        C70->setAutoFillBackground(true);
        C70->setFrameShape(QFrame::NoFrame);
        C70->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C70->setScaledContents(false);
        C40 = new QLabel(centralWidget);
        C40->setObjectName(QString::fromUtf8("C40"));
        C40->setGeometry(QRect(1020, 240, 80, 80));
        C40->setAutoFillBackground(true);
        C40->setFrameShape(QFrame::NoFrame);
        C40->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C40->setScaledContents(false);
        C60 = new QLabel(centralWidget);
        C60->setObjectName(QString::fromUtf8("C60"));
        C60->setGeometry(QRect(1020, 400, 80, 80));
        C60->setAutoFillBackground(true);
        C60->setFrameShape(QFrame::NoFrame);
        C60->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C60->setScaledContents(false);
        C30 = new QLabel(centralWidget);
        C30->setObjectName(QString::fromUtf8("C30"));
        C30->setGeometry(QRect(1020, 160, 80, 80));
        C30->setAutoFillBackground(true);
        C30->setFrameShape(QFrame::NoFrame);
        C30->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C30->setScaledContents(false);
        C50 = new QLabel(centralWidget);
        C50->setObjectName(QString::fromUtf8("C50"));
        C50->setGeometry(QRect(1020, 320, 80, 80));
        C50->setAutoFillBackground(true);
        C50->setFrameShape(QFrame::NoFrame);
        C50->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C50->setScaledContents(false);
        C90 = new QLabel(centralWidget);
        C90->setObjectName(QString::fromUtf8("C90"));
        C90->setGeometry(QRect(1020, 640, 80, 80));
        C90->setAutoFillBackground(true);
        C90->setFrameShape(QFrame::NoFrame);
        C90->setPixmap(QPixmap(QString::fromUtf8("caminoUnionVH.jpg")));
        C90->setScaledContents(false);
        crearmat = new QPushButton(centralWidget);
        crearmat->setObjectName(QString::fromUtf8("crearmat"));
        crearmat->setGeometry(QRect(70, 60, 89, 25));
        G2 = new QLabel(centralWidget);
        G2->setObjectName(QString::fromUtf8("G2"));
        G2->setGeometry(QRect(315, 40, 25, 25));
        G1 = new QLabel(centralWidget);
        G1->setObjectName(QString::fromUtf8("G1"));
        G1->setGeometry(QRect(315, 10, 25, 25));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(70, 220, 121, 25));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1297, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        C1->setText(QString());
        C2->setText(QString());
        C3->setText(QString());
        C4->setText(QString());
        C5->setText(QString());
        C6->setText(QString());
        C7->setText(QString());
        C8->setText(QString());
        C9->setText(QString());
        C10->setText(QString());
        C21->setText(QString());
        C11->setText(QString());
        C31->setText(QString());
        C41->setText(QString());
        C51->setText(QString());
        C61->setText(QString());
        C71->setText(QString());
        C81->setText(QString());
        C91->setText(QString());
        C12->setText(QString());
        C22->setText(QString());
        C32->setText(QString());
        C42->setText(QString());
        C52->setText(QString());
        C62->setText(QString());
        C72->setText(QString());
        C82->setText(QString());
        C92->setText(QString());
        C13->setText(QString());
        C63->setText(QString());
        C23->setText(QString());
        C43->setText(QString());
        C93->setText(QString());
        C73->setText(QString());
        C83->setText(QString());
        C53->setText(QString());
        C33->setText(QString());
        C74->setText(QString());
        C14->setText(QString());
        C94->setText(QString());
        C64->setText(QString());
        C34->setText(QString());
        C54->setText(QString());
        C24->setText(QString());
        C44->setText(QString());
        C84->setText(QString());
        C75->setText(QString());
        C15->setText(QString());
        C95->setText(QString());
        C65->setText(QString());
        C35->setText(QString());
        C55->setText(QString());
        C25->setText(QString());
        C45->setText(QString());
        C85->setText(QString());
        C76->setText(QString());
        C16->setText(QString());
        C96->setText(QString());
        C66->setText(QString());
        C36->setText(QString());
        C56->setText(QString());
        C26->setText(QString());
        C46->setText(QString());
        C86->setText(QString());
        C77->setText(QString());
        C17->setText(QString());
        C97->setText(QString());
        C67->setText(QString());
        C37->setText(QString());
        C57->setText(QString());
        C27->setText(QString());
        C47->setText(QString());
        C87->setText(QString());
        C78->setText(QString());
        C18->setText(QString());
        C98->setText(QString());
        C68->setText(QString());
        C38->setText(QString());
        C58->setText(QString());
        C28->setText(QString());
        C48->setText(QString());
        C88->setText(QString());
        C79->setText(QString());
        C19->setText(QString());
        C99->setText(QString());
        C69->setText(QString());
        C39->setText(QString());
        C59->setText(QString());
        C29->setText(QString());
        C49->setText(QString());
        C89->setText(QString());
        C80->setText(QString());
        C20->setText(QString());
        C100->setText(QString());
        C70->setText(QString());
        C40->setText(QString());
        C60->setText(QString());
        C30->setText(QString());
        C50->setText(QString());
        C90->setText(QString());
        crearmat->setText(QApplication::translate("MainWindow", "Simulacion", 0, QApplication::UnicodeUTF8));
        G2->setText(QApplication::translate("MainWindow", "TextLabel", 0, QApplication::UnicodeUTF8));
        G1->setText(QApplication::translate("MainWindow", "TextLabel", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("MainWindow", "Ver Generaciones", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
